### PR TITLE
Czech translation added

### PR DESCRIPTION
**Pull request by svetlemodry**
... for blue-chat.

### CODE REVIEW

**Comment by svetlemodry** [comment]
Any chance to have this PR merged or is the project dead?
Cheers.

**Comment by maysleazy** [comment]
Now I'm Working on the project, would implemet these asap :)

**Comment by svetlemodry** [comment]
Cool, thanks! Feel free to let me know should there be any updated strings for translation.

**Comment by balzathor** [comment]
Hey can you form a pull request into my profile's Bluechat, because Alex is no longer looking after it and its deprecated, So I'm updating it and taking care of it now :)

**Comment by balzathor** [comment]
[Here's](https://github.com/balzathor/Bleu) the link to my repository, would love to have more languages added to the repo when I get time :)

**Pull request closed without merging**
